### ISSUE TITLE
Cat Meow Sound Plays When Cat is Clicked

### ISSUE THREAD

**Issue by pepper-seattle** [pepper-seattle/catclicker_deluxe#3]
* Add audio file for cat (meow preferred, but not required if you can sell me on it)
* Audio queued for each click on cat

**Comment by AwsafAlam** [comment]
Can I have a go at this one?  😀

**Comment by pepper-seattle** [comment]
Sorry, I accepted code for this one, BUT you can add additional sounds! Really you can add anything you think would improve the game and I've just added some new ideas for people to try out if you're stumped.
